[features]
seeds = false
skip-lint = false
[programs.devnet]
utecsolanaprogram = "99S3oraEVfFhmQRDujuvkYYy1G4Ucbko4bTBXovnw3BB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jmirandd/.config/solana/id.json"

[scripts]
test = "node tests/utecsolanaprogram.js"
